#!/usr/bin/env python3
"""Verify competency descriptors stay in sync with the framework.

`competencies.yaml` is the canonical name list; `competencies/*.md` are the descriptors
generated by `import_competency_descriptors.py`. This check fails (exit 1) if they drift:

  * a framework competency has no descriptor (except exempt placeholders),
  * a descriptor names a competency that isn't in the framework,
  * a descriptor's frontmatter is malformed, self-reports `in_framework: false`,
  * or a descriptor's filename doesn't match its `slug`.

Run:  python scripts/check_competency_descriptors.py
Requires: pyyaml. Read-only — makes no changes.
"""
import sys
import pathlib

try:
    import yaml
except ImportError:
    sys.exit("pyyaml required: pip install pyyaml")

REPO = pathlib.Path(__file__).resolve().parent.parent
YAML = REPO / "competencies.yaml"
OUT = REPO / "competencies"

# Framework names that legitimately have no descriptor (no source content exists).
EXEMPT = {"Uncategorized"}


def parse_frontmatter(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    return yaml.safe_load(text[3:end])


def main():
    framework = {n for names in yaml.safe_load(YAML.read_text(encoding="utf-8")).values()
                 for n in names}
    errors, seen = [], {}

    for md in sorted(OUT.glob("*.md")):
        if md.name == "README.md":
            continue
        try:
            fm = parse_frontmatter(md)
        except yaml.YAMLError as e:
            errors.append(f"{md.name}: frontmatter does not parse ({e})")
            continue
        if not fm or "name" not in fm:
            errors.append(f"{md.name}: missing frontmatter or `name`")
            continue
        name = fm["name"]
        if name in seen:
            errors.append(f"{md.name}: duplicate descriptor for '{name}' (also {seen[name]})")
        seen[name] = md.name
        if fm.get("slug") and md.stem != fm["slug"]:
            errors.append(f"{md.name}: filename does not match slug '{fm['slug']}'")
        if name not in framework:
            errors.append(f"{md.name}: '{name}' is not in competencies.yaml")
        elif fm.get("in_framework") is False:
            errors.append(f"{md.name}: '{name}' self-reports in_framework: false")

    missing = sorted(framework - set(seen) - EXEMPT)
    for name in missing:
        errors.append(f"no descriptor for framework competency '{name}'")

    covered = len(framework & set(seen))
    print(f"framework: {len(framework)} competencies "
          f"({len(EXEMPT & framework)} exempt) · descriptors: {len(seen)} · "
          f"covered: {covered}")
    if errors:
        print(f"\n{len(errors)} problem(s):")
        for e in errors:
            print("  -", e)
        sys.exit(1)
    print("OK — descriptors and framework are in sync.")


if __name__ == "__main__":
    main()
