#!/usr/bin/env python3
"""Regenerate COVERAGE.md from competencies.yaml + module frontmatter.

Coverage = which of the 42 framework competencies have >=1 module, and which are gaps.
Reads ONLY competencies.yaml and modules/*/README.md frontmatter (the source-of-truth
split: workflow state lives in the GitHub Project, not here).

A frontmatter competency that isn't in competencies.yaml is a loud warning — it means a
typo is hiding a module from coverage. In CI this is treated as a failure (exit 1).
"""
import sys, pathlib, datetime

try:
    import yaml
except ImportError:
    sys.exit("pyyaml required: pip install pyyaml")

REPO = pathlib.Path(__file__).resolve().parent.parent


def parse_frontmatter(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    return yaml.safe_load(text[3:end]) or {}


def main():
    cats = yaml.safe_load((REPO / "competencies.yaml").read_text(encoding="utf-8"))
    all_names = {n for names in cats.values() for n in names}
    coverage = {n: [] for n in all_names}
    warnings = []

    for md in sorted((REPO / "modules").glob("*/README.md")):
        fm = parse_frontmatter(md)
        title = fm.get("title", md.parent.name)
        for c in fm.get("competencies", []) or []:
            if c in coverage:
                coverage[c].append(title)
            else:
                warnings.append(f"{md.parent.name}: competency '{c}' not in competencies.yaml")

    covered = sorted(c for c in all_names if coverage[c])
    gaps = sorted(c for c in all_names if not coverage[c])

    lines = [
        "<!-- AUTO-GENERATED by scripts/gen_coverage.py — do not edit by hand. -->",
        "# Competency Coverage",
        "",
        f"_Last generated: {datetime.date.today().isoformat()}._",
        "",
        f"**{len(covered)} of {len(all_names)} competencies have at least one module. "
        f"{len(gaps)} are gaps (no module yet).**",
        "",
    ]
    for cat, names in cats.items():
        lines.append(f"## {cat}")
        lines.append("")
        lines.append("| Competency | Modules | Status |")
        lines.append("| --- | --- | --- |")
        for name in names:
            mods = coverage.get(name, [])
            mark = "✅" if mods else "⛔ gap"
            lines.append(f"| {name} | {len(mods)} | {mark} |")
        lines.append("")
    lines.append("## Gaps — competencies with no module yet")
    lines.append("")
    lines += [f"- {g}" for g in gaps] or ["- _none_"]
    lines.append("")

    (REPO / "COVERAGE.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"covered={len(covered)} gaps={len(gaps)}")
    for w in warnings:
        print("WARNING:", w)
    if warnings:
        sys.exit(1)


if __name__ == "__main__":
    main()
