"""MkDocs build hooks (wired up by `hooks:` in mkdocs.yml).

Keeps the literate-nav source file out of the published site.

`scripts/gen_site.py` writes SUMMARY.md so mkdocs-literate-nav can build the navigation
from it, but every file in the collection is also built as a page — which published a
stray /SUMMARY/ page listing the raw nav. `exclude_docs` can't help: it filters the
docs_dir, and this file is generated by a plugin, not read off disk.

So the file is dropped in `on_nav`, which runs after literate-nav has already consumed
it and before MkDocs builds pages from the collection. Doing it here rather than deleting
the output in `on_post_build` also keeps the page out of sitemap.xml, which is built from
this same collection.
"""

NAV_FILE = "SUMMARY.md"


def on_nav(nav, config, files):
    """Drop the nav source file from the build once the nav has been assembled."""
    summary = files.get_file_from_path(NAV_FILE)
    if summary is not None:
        files.remove(summary)
    return nav
